### ISSUE TITLE
new feature : keep all episodes

### ISSUE THREAD

**Issue by adri123** [guyhoffman/podpuller#4]
apparently there is no possibilities to keep all episodes of a podcast.
It is possible to implement an option like `keep episodes = all` ?
Thanks,

**Comment by guyhoffman** [comment]
That's a good idea - as a workaround, you can set this to an insanely large number.

**Comment by guyhoffman** [comment]
This is now implemented in commit 51b46183b18d321d4861cb900d4be9afb78b4069
